"""
Builds ALL_SESSIONS_TRANSCRIPT.md -- one human-readable document combining
every chat/logs/session_*.jsonl file, in chronological order.

Each session_*.jsonl file (one per server run, written by
chat/logging_utils.py when ANLLMS_CHAT_LOG=1) is one JSON object per line:
{timestamp, user_message, assistant_content, tool_results}. This script
turns that raw JSONL into readable Markdown: per session, per turn, the
user's message, the assistant's reply text, any tool calls made, and
their results.

This is a plain script with no package imports, so it can be run
directly (no `-m` / absolute-import requirement like chat/server.py has):

    python chat/logs/build_transcript.py

Run it after a test session (or several) to refresh the combined
transcript. It is safe to re-run any time -- it always rebuilds the
whole document from whatever session_*.jsonl files currently exist in
this directory, so it never gets out of sync with them.
"""

from __future__ import annotations

import json
from pathlib import Path

_LOG_DIR = Path(__file__).parent
_OUTPUT_FILE = _LOG_DIR / "ALL_SESSIONS_TRANSCRIPT.md"


def _format_tool_use(block: dict) -> str:
    name = block.get("name", "unknown_tool")
    tool_input = block.get("input", {})
    return f"  - Called `{name}` with input: `{json.dumps(tool_input)}`"


def _format_tool_result(result: dict) -> str:
    content = result.get("content", "")
    return f"  - Result: {content}"


def _format_turn(entry: dict) -> str:
    lines = [f"**[{entry.get('timestamp', 'unknown time')}]**", ""]
    lines.append(f"**User:** {entry.get('user_message', '')}")
    lines.append("")

    assistant_content = entry.get("assistant_content", [])
    text_parts = [b.get("text", "") for b in assistant_content if b.get("type") == "text"]
    tool_use_blocks = [b for b in assistant_content if b.get("type") == "tool_use"]

    if text_parts:
        lines.append(f"**Assistant:** {' '.join(text_parts)}")
        lines.append("")

    if tool_use_blocks:
        lines.append("**Tool calls:**")
        for block in tool_use_blocks:
            lines.append(_format_tool_use(block))
        lines.append("")

    tool_results = entry.get("tool_results", [])
    if tool_results:
        lines.append("**Tool results:**")
        for result in tool_results:
            lines.append(_format_tool_result(result))
        lines.append("")

    return "\n".join(lines)


def build_transcript() -> Path:
    session_files = sorted(_LOG_DIR.glob("session_*.jsonl"))

    out_lines = [
        "# ANLLMS Chat -- All Test Session Transcripts",
        "",
        "Auto-generated by `chat/logs/build_transcript.py` from every",
        "`session_*.jsonl` file in this directory. Do not hand-edit -- re-run",
        "the script to regenerate after new test sessions instead.",
        "",
        f"Sessions included: {len(session_files)}",
        "",
    ]

    if not session_files:
        out_lines.append("*No session_*.jsonl files found in chat/logs/ yet.*")
    else:
        for session_file in session_files:
            out_lines.append("---")
            out_lines.append("")
            out_lines.append(f"## Session: `{session_file.name}`")
            out_lines.append("")
            with open(session_file) as f:
                for line_num, line in enumerate(f, start=1):
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        entry = json.loads(line)
                    except json.JSONDecodeError:
                        out_lines.append(
                            f"*[malformed JSON on line {line_num} of "
                            f"{session_file.name} -- skipped]*"
                        )
                        continue
                    out_lines.append(_format_turn(entry))
                    out_lines.append("")

    _OUTPUT_FILE.write_text("\n".join(out_lines))
    return _OUTPUT_FILE


if __name__ == "__main__":
    path = build_transcript()
    print(f"Wrote {path}")
